/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'main-syndplus-final'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct __iobuf;

/* 1 */
struct TbLoadFiles
{
  char FName[28];
  void **Start;
  void **SEnd;
  void **SLength;
  __int16 Flags;
  __int16 Spare;
};

/* 2 */
struct drvr_desc
{
  int min_API_version;
  int drvr_type;
  char data_suffix[4];
  void *dev_name_table;
  int default_IO;
  int default_IRQ;
  int default_DMA;
  int default_DRQ;
  int service_rate;
  int display_size;
};

/* 3 */
typedef struct __iobuf FILE;

/* 4 */
#pragma pack(push, 1)
struct __iobuf
{
  unsigned __int8 *_ptr;
  int _cnt;
  unsigned __int8 *_base;
  unsigned int _flag;
  int _handle;
  unsigned int _bufsize;
  unsigned __int8 _ungotten;
  unsigned __int8 _tmpfchar;
};
#pragma pack(pop)

/* 5 */
struct __attribute__((packed)) __attribute__((aligned(2))) TbSprite
{
  unsigned __int8 *Data;
  char SWidth;
  char SHeight;
};

