/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'main-syndplus-final'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct __iobuf;

/* 1 */
struct TbLoadFiles
{
  char FName[28];
  void **Start;
  void **SEnd;
  int SLength;
  __int16 Flags;
  __int16 Spare;
};

/* 2 */
struct drvr_desc
{
  int min_API_version;
  int drvr_type;
  char data_suffix[4];
  void *dev_name_table;
  int default_IO;
  int default_IRQ;
  int default_DMA;
  int default_DRQ;
  int service_rate;
  int display_size;
};

/* 3 */
typedef struct __iobuf FILE;

/* 4 */
#pragma pack(push, 1)
struct __iobuf
{
  unsigned __int8 *_ptr;
  int _cnt;
  unsigned __int8 *_base;
  unsigned int _flag;
  int _handle;
  unsigned int _bufsize;
  unsigned __int8 _ungotten;
  unsigned __int8 _tmpfchar;
};
#pragma pack(pop)

/* 5 */
struct __attribute__((packed)) __attribute__((aligned(2))) TbSprite
{
  unsigned __int8 *Data;
  char SWidth;
  char SHeight;
};

/* 6 */
struct Packet
{
  __int16 Data0;
  __int16 Data1;
  __int16 Data2;
  __int16 Seed;
  __int16 field_8;
  __int16 Gameturn;
  char field_C;
  char Action;
};

/* 7 */
enum PacketActions
{
  PAct_NONE = 0x0,
  PAct_1 = 0x1,
  PAct_2 = 0x2,
  PAct_3 = 0x3,
  PAct_4 = 0x4,
  PAct_5 = 0x5,
  PAct_6 = 0x6,
  PAct_7 = 0x7,
  PAct_8 = 0x8,
  PAct_9 = 0x9,
  PAct_a = 0xA,
  PAct_b = 0xB,
  PAct_c = 0xC,
  PAct_d = 0xD,
  PAct_e = 0xE,
  PAct_f = 0xF,
  PAct_10 = 0x10,
  PAct_11 = 0x11,
  PAct_12 = 0x12,
  PAct_13 = 0x13,
  PAct_14 = 0x14,
  PAct_15 = 0x15,
  PAct_16 = 0x16,
  PAct_17 = 0x17,
  PAct_18 = 0x18,
  PAct_19 = 0x19,
  PAct_1a = 0x1A,
  PAct_1b = 0x1B,
  PAct_1c = 0x1C,
  PAct_1d = 0x1D,
  PAct_1e = 0x1E,
  PAct_1f = 0x1F,
  PAct_20 = 0x20,
  PAct_21 = 0x21,
  PAct_22 = 0x22,
  PAct_23 = 0x23,
  PAct_24 = 0x24,
  PAct_25 = 0x25,
  PAct_26 = 0x26,
  PAct_27 = 0x27,
  PAct_28 = 0x28,
  PAct_29 = 0x29,
  PAct_2a = 0x2A,
  PAct_2b = 0x2B,
  PAct_2c = 0x2C,
  PAct_2d = 0x2D,
  PAct_2e = 0x2E,
  PAct_2f = 0x2F,
  PAct_30 = 0x30,
  PAct_31 = 0x31,
  PAct_32 = 0x32,
  PAct_33 = 0x33,
  PAct_34 = 0x34,
  PAct_35 = 0x35,
  PAct_36 = 0x36,
  PAct_37 = 0x37,
  PAct_38 = 0x38,
  PAct_39 = 0x39,
  PAct_3a = 0x3A,
};

/* 8 */
struct __attribute__((packed)) __attribute__((aligned(1))) NCB
{
  char Command;
  char RetCode;
  char Lsn;
  char Num;
  __int16 BufferPtr;
  __int16 BufferPtrSeg;
  __int16 Length;
  char CallName[16];
  char Name[16];
  char Rto;
  char Sto;
  int Post;
  char LanaNum;
  char CmdCPlt;
  char Reserve[14];
  char Segment;
};

/* 9 */
struct DWORDREGS
{
  int r_eax;
  int r_ebx;
  int r_ecx;
  int r_edx;
  int r_esi;
  int r_edi;
  int cflag;
};

/* 10 */
struct BFSample
{
  int field_0;
  int field_4;
  int field_8;
  __int16 field_C;
  __attribute__((packed)) __attribute__((aligned(1))) int data_shifted;
  __attribute__((packed)) __attribute__((aligned(1))) void *data_start;
  __int16 field_16;
  int field_18;
  __int16 field_1C;
  char field_1E;
  char field_1F;
};

/* 11 */
struct BFSampleStatus
{
  char field_0;
  char field_1;
};

/* 12 */
struct __attribute__((packed)) __attribute__((aligned(2))) NCBAlloc
{
  struct NCB *NCB;
  __int16 Selector;
};

/* 13 */
enum DrawFlagsVals
{
  DrwF_ScreenMCGA = 0x1,
  DrwF_ScreenVres16 = 0x2,
  DrwF_Unkn04 = 0x4,
};

/* 15 */
struct struc_1E9_sub1
{
  __int16 field_0;
  __int16 field_2[22];
  __int16 field_2E;
};

/* 14 */
struct __attribute__((packed)) __attribute__((aligned(1))) struc_1E9
{
  char field_0;
  char field_1;
  char field_2;
  int field_3;
  struc_1E9_sub1 field_7[10];
  __int16 field_1E7;
};

/* 16 */
struct __attribute__((packed)) __attribute__((aligned(2))) struc_5539C
{
  __int16 field_0[1];
  char field_2[1];
  char field_3[1];
  char field_4;
  char field_5;
  int field_6;
};

/* 35 */
struct PlayerSubStr1
{
  char field_0;
  __attribute__((packed)) __attribute__((aligned(1))) __int16 field_1;
  __attribute__((packed)) __attribute__((aligned(1))) __int16 field_3;
  __attribute__((packed)) __attribute__((aligned(1))) __int16 field_5;
  char field_7;
  __int16 field_8;
  __int16 field_A;
  __int16 field_C;
  char field_E[22];
  __int16 field_24;
  __int16 field_26;
};

/* 18 */
struct __attribute__((packed)) __attribute__((aligned(1))) PlayerInfo
{
  int Credits;
  int field_4;
  __int16 field_8;
  __int16 field_A;
  __int16 field_C;
  char FlagsE;
  char field_F;
  char field_10;
  char field_11[18];
  char field_23[146];
  unsigned __int8 field_B5;
  char field_B6;
  __int16 field_B7;
  char field_B9[50];
  char field_EB[16];
  __int16 field_FB;
  char field_FD[32];
  PlayerSubStr1 substrct_11D[18];
  char field_3ED[30];
  __int16 field_40B[5];
  __int16 field_415;
};

/* 19 */
struct __attribute__((packed)) __attribute__((aligned(1))) struc_57BF4
{
  char field_0[1];
  int field_1;
  __int16 field_5;
  int field_7;
  __int16 field_B;
  int field_D;
  __int16 field_11;
  __int16 field_13[23];
  __int16 field_41[217];
  char field_1F3[1];
  char field_1F4;
};

/* 20 */
struct __attribute__((packed)) __attribute__((aligned(1))) struc_55780
{
  unsigned __int8 field_0;
  int Cost;
  char field_5;
  __int16 field_6;
  __int16 field_8;
  __int16 field_A[240];
  char field_1EA;
};

/* 21 */
struct Person
{
  __int16 PrevMapWho;
  __int16 NextMapWho;
  __int16 X;
  __int16 Y;
  __int16 Z;
  unsigned __int16 Flags;
  __int16 field_C;
  __int16 field_E;
  __int16 Frame;
  __int16 StartFrame;
  __int16 field_14;
  unsigned __int16 field_16;
  char field_18;
  unsigned __int8 State;
  unsigned __int8 field_1A;
  char field_1B;
  char field_1C;
  char field_1D;
  __int16 field_1E;
  unsigned __int16 UnkPersonOffs;
  __int16 PassengerNext;
  __int16 field_24;
  __int16 ComCur;
  __int16 StartCommand;
  unsigned __int16 Target;
  __int16 Data;
  __int16 GotoX;
  __int16 GotoY;
  __int16 GotoZ;
  __int16 LastXpos;
  __int16 LastYpos;
  __int16 HugGotoZ;
  __int16 ChildWeapon;
  __int16 Equipment;
  __int16 field_3E;
  __int16 field_40;
  __int16 field_42;
  __int16 CurrentWeapon;
  char field_46;
  char field_47;
  char field_48;
  char field_49;
  char field_4A;
  char field_4B;
  char field_4C;
  char field_4D;
  char field_4E;
  char field_4F;
  char field_50;
  char field_51;
  char field_52;
  char field_53;
  unsigned __int8 field_54;
  unsigned __int8 field_55;
  __int16 field_56;
  char field_58;
  char field_59;
  __int16 field_5A;
};

/* 23 */
struct Vehicle
{
  __int16 PrevMapWho;
  __int16 NextMapWho;
  __int16 X;
  __int16 Y;
  __int16 Z;
  unsigned __int16 Flags;
  __int16 field_C;
  __int16 field_E;
  __int16 Frame;
  __int16 StartFrame;
  __int16 field_14;
  __int16 field_16;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  unsigned __int16 PassengerHead;
  __int16 field_1E;
  __int16 field_20;
  __int16 field_22;
  __int16 field_24;
  __int16 field_26;
  __int16 field_28;
};

/* 24 */
struct Object
{
  __int16 PrevMapWho;
  __int16 NextMapWho;
  __int16 X;
  __int16 Y;
  __int16 Z;
  unsigned __int16 Flags;
  __int16 field_C;
  __int16 field_E;
  __int16 Frame;
  __int16 StartFrame;
  __int16 field_14;
  __int16 field_16;
  char field_18;
  char field_19;
  char field_1A;
  char field_1B;
  __int16 field_1C;
};

/* 25 */
struct Weapon
{
  __int16 PrevMapWho;
  __int16 NextMapWho;
  __int16 X;
  __int16 Y;
  __int16 Z;
  unsigned __int16 Flags;
  __int16 field_C;
  __attribute__((packed)) __attribute__((aligned(1))) int field_E;
  __int16 field_12;
  __int16 field_14;
  __int16 field_16;
  char field_18;
  unsigned __int8 field_19;
  char field_1A;
  char field_1B;
  __int16 PersonsNext;
  __int16 field_1E;
  __int16 field_20;
  __int16 field_22;
};

/* 26 */
struct Effect
{
  __int16 PrevMapWho;
  __int16 NextMapWho;
  __int16 X;
  __int16 Y;
  __int16 Z;
  unsigned __int16 Flags;
  __int16 field_C;
  __int16 field_E;
  __int16 field_10;
  __int16 field_12;
  __int16 field_14;
  __int16 field_16;
  char field_18;
  char field_19;
  __int16 field_1A;
  __int16 field_1C;
};

/* 27 */
struct Command
{
  __int16 Next;
  __int16 OtherThing;
  unsigned __int8 X;
  unsigned __int8 Y;
  unsigned __int8 Z;
  unsigned __int8 Type;
};

/* 28 */
enum PersonCommandType
{
  PCmd_NONE = 0x0,
  PCmd_GOTO_POINT = 0x1,
  PCmd_GOTO_STRUCTURE2 = 0x2,
  PCmd_LEAVE_VEHICLE = 0x3,
  PCmd_WAIT_FOR_MODEL = 0x4,
  PCmd_WAIT_FOR_TIME = 0x5,
  PCmd_GOTO_STRUCTURE6 = 0x6,
  PCmd_FAIL_LEVEL = 0x7,
  PCmd_WAIT_FOR_TRIGGER = 0x8,
  PCmd_END_COMMANDS = 0x9,
  PCmd_ALLOW_PASSENGERS = 0xA,
  PCmd_COMPLETE_LEVEL = 0xB,
  PCmd_TOTAL_COMMANDS = 0xC,
};

/* 29 */
enum PersonState
{
  PerSt_NONE = 0x0,
  PerSt_NEXT_COMMAND = 0x1,
  PerSt_GOTO_POINT2 = 0x2,
  PerSt_GOTO_POINT3 = 0x3,
  PerSt_GOTO_STRUCTURE4 = 0x4,
  PerSt_GOTO_STRUCTURE5 = 0x5,
  PerSt_MOVE_INTO_VEHICLE = 0x6,
  PerSt_MOVE_OUT_OF_VEHICLE = 0x7,
  PerSt_PASSENGER = 0x8,
  PerSt_PICKUP_WEAPON = 0x9,
  PerSt_DROP_WEAPON = 0xA,
  PerSt_SELECT_WEAPON = 0xB,
  PerSt_WAIT_FOR_MODEL = 0xC,
  PerSt_WAIT_FOR_TIME = 0xD,
  PerSt_HUG_RIGHT = 0xE,
  PerSt_HUG_LEFT = 0xF,
  PerSt_WAITING_TO_MOVE = 0x10,
  PerSt_HIT_BY_LASER = 0x11,
  PerSt_HIT_BY_BULLET = 0x12,
  PerSt_HIT_BY_VEHICLE = 0x13,
  PerSt_HIT_BY_FIRE = 0x14,
  PerSt_HIT_BY_EXPLOSION = 0x15,
  PerSt_FLY_BACK = 0x16,
  PerSt_ON_FIRE = 0x17,
  PerSt_DYING = 0x18,
  PerSt_DYING_ON_FIRE = 0x19,
  PerSt_DEAD = 0x1A,
  PerSt_DEAD_ON_FIRE = 0x1B,
  PerSt_GUARD_AREA = 0x1C,
  PerSt_WANDER = 0x1D,
  PerSt_PERSUADED = 0x1E,
  PerSt_RUNAWAY = 0x1F,
  PerSt_FOLLOW_AND_ATTACK = 0x20,
  PerSt_DROWN = 0x21,
  PerSt_GIVE_WARNING = 0x22,
  PerSt_ASHES = 0x23,
  PerSt_CHECK_CROSS_ROAD = 0x24,
  PerSt_CROSS_ROAD = 0x25,
  PerSt_WAIT_TO_CROSS_ROAD = 0x26,
  PerSt_WALK_OFF_ROAD = 0x27,
  PerSt_WAIT_FOR_TRIGGER = 0x28,
  PerSt_WAIT_FOR_TRAIN = 0x29,
  PerSt_ALLOW_PASSENGERS = 0x2A,
  PerSt_USE_WEAPON = 0x2B,
  PerSt_BEING_PERSUADED = 0x2C,
  PerSt_TOTAL_STATES = 0x2D,
};

/* 30 */
struct ComputerPlayer
{
  unsigned __int8 ObjectiveNo;
  char field_1;
  char field_2;
  char field_3;
  char field_4;
  char field_5;
  unsigned __int8 field_6;
  unsigned __int8 field_7;
  char field_8;
  char field_9;
  __int16 field_A;
  void *ptrfield_C;
  struct Person *field_10;
};

/* 31 */
struct __attribute__((packed)) __attribute__((aligned(1))) CPObjective
{
  __int16 Child;
  unsigned __int16 Parent;
  __int16 field_4;
  char field_6;
  char ActionType;
  char Action;
  unsigned __int16 X;
  __int16 Y;
  __int16 Z;
};

/* 32 */
struct __attribute__((packed)) __attribute__((aligned(2))) Objective
{
  int field_0;
  __int16 field_4;
  unsigned __int16 field_6;
  __int16 field_8;
  __int16 field_A;
  __int16 field_C;
};

/* 33 */
struct __attribute__((packed)) __attribute__((aligned(1))) Thing
{
  unsigned __int16 PrevMapWho;
  __int16 NextMapWho;
  __int16 X;
  __int16 Y;
  __int16 Z;
  unsigned __int16 Flags;
  char field_C[2];
  char field_E;
  char field_F;
  __int16 Frame;
  __int16 StartFrame;
  char field_14[3];
  char field_17;
  char field_18;
};

/* 34 */
enum KeyCodes
{
  KC_UNASSIGNED = 0x0,
  KC_ESCAPE = 0x1,
  KC_1 = 0x2,
  KC_2 = 0x3,
  KC_3 = 0x4,
  KC_4 = 0x5,
  KC_5 = 0x6,
  KC_6 = 0x7,
  KC_7 = 0x8,
  KC_8 = 0x9,
  KC_9 = 0xA,
  KC_0 = 0xB,
  KC_MINUS = 0xC,
  KC_EQUALS = 0xD,
  KC_BACK = 0xE,
  KC_TAB = 0xF,
  KC_Q = 0x10,
  KC_W = 0x11,
  KC_E = 0x12,
  KC_R = 0x13,
  KC_T = 0x14,
  KC_Y = 0x15,
  KC_U = 0x16,
  KC_I = 0x17,
  KC_O = 0x18,
  KC_P = 0x19,
  KC_LBRACKET = 0x1A,
  KC_RBRACKET = 0x1B,
  KC_RETURN = 0x1C,
  KC_LCONTROL = 0x1D,
  KC_A = 0x1E,
  KC_S = 0x1F,
  KC_D = 0x20,
  KC_F = 0x21,
  KC_G = 0x22,
  KC_H = 0x23,
  KC_J = 0x24,
  KC_K = 0x25,
  KC_L = 0x26,
  KC_SEMICOLON = 0x27,
  KC_APOSTROPHE = 0x28,
  KC_GRAVE = 0x29,
  KC_LSHIFT = 0x2A,
  KC_BACKSLASH = 0x2B,
  KC_Z = 0x2C,
  KC_X = 0x2D,
  KC_C = 0x2E,
  KC_V = 0x2F,
  KC_B = 0x30,
  KC_N = 0x31,
  KC_M = 0x32,
  KC_COMMA = 0x33,
  KC_PERIOD = 0x34,
  KC_SLASH = 0x35,
  KC_RSHIFT = 0x36,
  KC_MULTIPLY = 0x37,
  KC_LALT = 0x38,
  KC_SPACE = 0x39,
  KC_CAPITAL = 0x3A,
  KC_F1 = 0x3B,
  KC_F2 = 0x3C,
  KC_F3 = 0x3D,
  KC_F4 = 0x3E,
  KC_F5 = 0x3F,
  KC_F6 = 0x40,
  KC_F7 = 0x41,
  KC_F8 = 0x42,
  KC_F9 = 0x43,
  KC_F10 = 0x44,
  KC_NUMLOCK = 0x45,
  KC_SCROLL = 0x46,
  KC_NUMPAD7 = 0x47,
  KC_NUMPAD8 = 0x48,
  KC_NUMPAD9 = 0x49,
  KC_SUBTRACT = 0x4A,
  KC_NUMPAD4 = 0x4B,
  KC_NUMPAD5 = 0x4C,
  KC_NUMPAD6 = 0x4D,
  KC_ADD = 0x4E,
  KC_NUMPAD1 = 0x4F,
  KC_NUMPAD2 = 0x50,
  KC_NUMPAD3 = 0x51,
  KC_NUMPAD0 = 0x52,
  KC_DECIMAL = 0x53,
  KC_OEM_102 = 0x56,
  KC_F11 = 0x57,
  KC_F12 = 0x58,
  KC_F13 = 0x64,
  KC_F14 = 0x65,
  KC_F15 = 0x66,
  KC_KANA = 0x70,
  KC_ABNT_C1 = 0x73,
  KC_CONVERT = 0x79,
  KC_NOCONVERT = 0x7B,
  KC_YEN = 0x7D,
  KC_ABNT_C2 = 0x7E,
  KC_NUMPADEQUALS = 0x8D,
  KC_PREVTRACK = 0x90,
  KC_AT = 0x91,
  KC_COLON = 0x92,
  KC_UNDERLINE = 0x93,
  KC_KANJI = 0x94,
  KC_STOP = 0x95,
  KC_AX = 0x96,
  KC_UNLABELED = 0x97,
  KC_NEXTTRACK = 0x99,
  KC_NUMPADENTER = 0x9C,
  KC_RCONTROL = 0x9D,
  KC_MUTE = 0xA0,
  KC_CALCULATOR = 0xA1,
  KC_PLAYPAUSE = 0xA2,
  KC_MEDIASTOP = 0xA4,
  KC_VOLUMEDOWN = 0xAE,
  KC_VOLUMEUP = 0xB0,
  KC_WEBHOME = 0xB2,
  KC_NUMPADCOMMA = 0xB3,
  KC_DIVIDE = 0xB5,
  KC_SYSRQ = 0xB7,
  KC_RALT = 0xB8,
  KC_PAUSE = 0xC5,
  KC_HOME = 0xC7,
  KC_UP = 0xC8,
  KC_PGUP = 0xC9,
  KC_LEFT = 0xCB,
  KC_RIGHT = 0xCD,
  KC_END = 0xCF,
  KC_DOWN = 0xD0,
  KC_PGDOWN = 0xD1,
  KC_INSERT = 0xD2,
  KC_DELETE = 0xD3,
  KC_LWIN = 0xDB,
  KC_RWIN = 0xDC,
  KC_APPS = 0xDD,
  KC_POWER = 0xDE,
  KC_SLEEP = 0xDF,
  KC_WAKE = 0xE3,
};

/* 36 */
struct UnkArr55256
{
  __int16 field_0;
  __int16 field_2;
  __int16 field_4;
  __int16 field_6;
  __int16 field_8;
  char field_A;
  char field_B;
  unsigned __int16 field_C;
  __int16 field_E;
  __int16 field_10;
};

/* 37 */
struct Frame
{
  __int16 FirstElement;
  char SWidth;
  char SHeight;
  char FX;
  char Flags;
  __int16 Next;
};

/* 38 */
struct SndArray
{
  __int16 field_0;
  __int16 field_2;
};

/* 39 */
struct __attribute__((packed)) __attribute__((aligned(2))) RMREGS
{
  char field_0[16];
  struct NCB *field_10;
  char field_14[8];
  int field_1C;
  __int16 field_20;
  __int16 field_22;
  __int16 field_24;
  char field_26[11];
  char field_31;
};

/* 40 */
struct NetBuffer
{
  __int16 Seg;
  __attribute__((packed)) __attribute__((aligned(1))) unsigned __int8 *Ptr;
  __int16 Selectr;
};

